services:
  database:
    image: "postgres:14.4-alpine"
    ports:
      - "5432:5432"
    volumes:
      - ams:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

volumes:
  ams:
